name: Feature Request
description: Features you would like to be added to Neokikoeru
labels: [enhancement]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant context, screenshots, or information you think might be helpful
